/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administrador;

import datos.VehiculoDAO;
import modelo.Vehiculo;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

public class ActualizarVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form SolicitudesProveedor
     */
    public ActualizarVehiculos() {
        initComponents();
        setLocationRelativeTo(null);
        actualizarTablaVehiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        btonVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbleVehiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btonStock = new javax.swing.JButton();
        btonlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btonVehiculo.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonVehiculo.setText("SOLICITAR NUEVO VEHICULO");
        btonVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonVehiculoActionPerformed(evt);
            }
        });

        tbleVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Color", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbleVehiculos);

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock de Vehiculos");

        btonStock.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonStock.setText("SOLICITAR CAMBIO DE STOCK");
        btonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonStockActionPerformed(evt);
            }
        });

        btonlogout.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonlogout.setText("Volver");
        btonlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btonlogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(btonStock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btonVehiculo)
                                .addGap(60, 60, 60)))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btonVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btonStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btonlogout)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonVehiculoActionPerformed

        SolicitarVehiculo solicitarVehiculo = new SolicitarVehiculo();
        solicitarVehiculo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btonVehiculoActionPerformed

    private void btonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonStockActionPerformed

        int selectedRow = tbleVehiculos.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un vehículo para solicitar stock.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tbleVehiculos.getModel();
        String marca = (String) model.getValueAt(selectedRow, 0);
        String modelo = (String) model.getValueAt(selectedRow, 1);
        String color = (String) model.getValueAt(selectedRow, 2);
        int stock = (int) model.getValueAt(selectedRow, 3);

        // Obtener el precio del vehículo
        VehiculoDAO vehiculoDAO = new VehiculoDAO();
        Vehiculo vehiculo = vehiculoDAO.obtenerPorMarcaModeloColor(marca, modelo, color);
        double precio = vehiculo != null ? vehiculo.getPrecio() : 0.0;

        SolicitarStock solicitarStock = new SolicitarStock(marca, modelo, color, stock, precio);
        solicitarStock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btonStockActionPerformed

    private void btonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonlogoutActionPerformed
        
        InterfazAdministrador iad = new InterfazAdministrador();
        iad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btonlogoutActionPerformed

    public void actualizarTablaVehiculos() {
        VehiculoDAO vehiculoDAO = new VehiculoDAO();
        List<Vehiculo> vehiculos = vehiculoDAO.seleccionarTodos();

        DefaultTableModel model = (DefaultTableModel) tbleVehiculos.getModel();
        model.setRowCount(0);
        for (Vehiculo vehiculo : vehiculos) {
            model.addRow(new Object[]{vehiculo.getMarca(), vehiculo.getModelo(), vehiculo.getColor(), vehiculo.getStock()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonStock;
    private javax.swing.JButton btonVehiculo;
    private javax.swing.JButton btonlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tbleVehiculos;
    // End of variables declaration//GEN-END:variables
}
