/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administrador;

import datos.MensajeDAO;
import java.sql.Timestamp;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import javax.swing.JOptionPane;
import modelo.Mensaje;

public class SolicitarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form SolicitarVehiculo
     */
    public SolicitarVehiculo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btonCancelar = new javax.swing.JButton();
        btonEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btonCancelar1 = new javax.swing.JButton();
        btonEnviar1 = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();

        btonCancelar.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonCancelar.setText("Cancelar");
        btonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonCancelarActionPerformed(evt);
            }
        });

        btonEnviar.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonEnviar.setText("Enviar");
        btonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonEnviarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Solicitud de Stock");

        btonCancelar1.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonCancelar1.setText("Cancelar");
        btonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonCancelar1ActionPerformed(evt);
            }
        });

        btonEnviar1.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        btonEnviar1.setText("Enviar");
        btonEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonEnviar1ActionPerformed(evt);
            }
        });

        txtPrecio.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("NSimSun", 1, 12))); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        txtMarca.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        txtMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese su Marca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("NSimSun", 1, 12))); // NOI18N

        txtColor.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        txtColor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese su Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("NSimSun", 1, 12))); // NOI18N

        txtModelo.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        txtModelo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese su Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("NSimSun", 1, 12))); // NOI18N

        txtStock.setFont(new java.awt.Font("NSimSun", 3, 14)); // NOI18N
        txtStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese el Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("NSimSun", 1, 12))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btonCancelar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btonEnviar1)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btonCancelar1)
                    .addComponent(btonEnviar1))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonCancelarActionPerformed
        
    }//GEN-LAST:event_btonCancelarActionPerformed

    private void btonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btonEnviarActionPerformed

    private void btonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonCancelar1ActionPerformed
        
        this.dispose();
        ActualizarVehiculos actualizarVehiculos = new ActualizarVehiculos();
        actualizarVehiculos.setVisible(true);
    }//GEN-LAST:event_btonCancelar1ActionPerformed

    private void btonEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonEnviar1ActionPerformed
        
        String marca = txtMarca.getText().trim();
        String modelo = txtModelo.getText().trim();
        String color = txtColor.getText().trim();
        double precio;
        int stock;

        try {
            precio = Double.parseDouble(txtPrecio.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un precio válido.");
            return;
        }

        try {
            stock = Integer.parseInt(txtStock.getText().trim());
            if (stock < 1 || stock > 5) {
                JOptionPane.showMessageDialog(this, "El stock debe ser entre 1 y 5.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un stock válido.");
            return;
        }

        String mensajeTexto = String.format(
            "Buenas Tardes Señor Proveedor,\n\nLe envío este mensaje para solicitar un nuevo vehículo.\n"
            + "Necesito que me consiga un nuevo vehículo con las siguientes características:\n"
            + "Marca: %s\nModelo: %s\nColor: %s\nPrecio: %.2f\nStock: %d\n\n"
            + "Espero su respuesta. Muchas gracias.",
            marca, modelo, color, precio, stock);

        Mensaje mensaje = new Mensaje();
        mensaje.setEmisorId(1); // Id del Administrador
        mensaje.setReceptorId(3); // Id del Proveedor
        mensaje.setTipoEmisor("Administrador");
        mensaje.setTipoReceptor("Proveedor");
        mensaje.setMensaje(mensajeTexto);

        // Obtener la fecha y hora actuales con la zona horaria correcta
        ZoneId zoneId = ZoneId.of("America/Lima"); // Cambia esto a tu zona horaria deseada
        ZonedDateTime zonedDateTime = ZonedDateTime.now(zoneId);
        Timestamp fechaActual = Timestamp.valueOf(zonedDateTime.toLocalDateTime());
        mensaje.setFecha(fechaActual);

        MensajeDAO mensajeDAO = new MensajeDAO();
        int resultado = mensajeDAO.insertar(mensaje);

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "Mensaje enviado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al enviar el mensaje.");
        }

        this.dispose();
        ActualizarVehiculos actualizarVehiculos = new ActualizarVehiculos();
        actualizarVehiculos.setVisible(true);
    }//GEN-LAST:event_btonEnviar1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonCancelar;
    private javax.swing.JButton btonCancelar1;
    private javax.swing.JButton btonEnviar;
    private javax.swing.JButton btonEnviar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
